//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMSWebPortal.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Application
    {
        public int Appl_ID { get; set; }
        public string Appl_Course { get; set; }
        public byte[] Appl_Img { get; set; }
        public string Appl_Name { get; set; }
        public string Appl_Email { get; set; }
        public Nullable<System.DateTime> Appl_DOB { get; set; }
        public string Appl_Contact { get; set; }
        public string Appl_Fname { get; set; }
        public string Appl_Mname { get; set; }
        public string Appl_Address { get; set; }
        public string Appl_City { get; set; }
        public string Appl_State { get; set; }
        public string Appl_Pin { get; set; }
        public string Appl_ParentEmail { get; set; }
        public string Appl_Qualification1 { get; set; }
        public string Appl_Qualification2 { get; set; }
        public string Appl_Qualification3 { get; set; }
        public string Appl_Lang1 { get; set; }
        public string Appl_Lang2 { get; set; }
        public string Appl_Lang3 { get; set; }
        public string Appl_Lang4 { get; set; }
        public string Appl_Relation1 { get; set; }
        public string Appl_Relation2 { get; set; }
        public string Appl_Relation3 { get; set; }
        public string Appl_Relation4 { get; set; }
        public string Appl_ExtraActivity { get; set; }
        public string Appl_ExtraInfo { get; set; }
        public Nullable<System.DateTime> Appl_Date { get; set; }
    }
}
